### PR TITLE
Code style fixes for way_planner

### PR DESCRIPTION
**Pull request by luca-fancellu**
### Fixed bug
Code style fixes

### Fix applied
Removed trailing spaces, formatted code

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@luca-fancellu Since you're working on the formatting, would you mind adding and running `roslint` so the formatting can be enforced?

**Comment by luca-fancellu** [comment]
> @luca-fancellu Since you're working on the formatting, would you mind adding and running `roslint` so the formatting can be enforced?

Done

**Comment by luca-fancellu** [comment]
@JWhitleyWork I think there is something wrong with the CI but I can't re-trigger any job

**Comment by JWhitleyWork** [comment]
@luca-fancellu It looks like `ros.org` was allowed to expire this morning. Access to it around the world is now intermittent. A trick for re-triggering CI, though: close the PR and re-open it.

**Review by JWhitleyWork — APPROVED** [review]
Thanks!

**Comment by luca-fancellu** [comment]
> @luca-fancellu It looks like `ros.org` was allowed to expire this morning. Access to it around the world is now intermittent. A trick for re-triggering CI, though: close the PR and re-open it.

Cool! Thanks for the trick!

**Pull request merged**
