### PR TITLE
lane select: Refactor waypoints publishing

### PR DESCRIPTION
**Pull request by icolwell-as**
Transferred from GitLab. See original PR for details:
https://gitlab.com/autowarefoundation/autoware.ai/core_planning/-/merge_requests/91

### CODE REVIEW

**Comment by icolwell-as** [comment]
@JWhitleyWork, any idea why it says the signoff is missing?
This is the commit:
> See merge request astuff/autoware.ai/core_planning!33
> Signed-off-by: Ian Colwell <icolwell@autonomoustuff.com>

**Comment by JWhitleyWork** [comment]
> any idea why it says the signoff is missing?

There are two commits in the MR. They both have to be signed.

**Comment by JWhitleyWork** [comment]
Additionally, there are conflicts in this MR now so it will require a rebase.

**Comment by JWhitleyWork** [comment]
Ping, @icolwell-as

**Review by JWhitleyWork — APPROVED** [review]

**Pull request merged**
