### PR TITLE
Twist Gate Refactor

### PR DESCRIPTION
**Pull request by icolwell-as**
- Removed remote control functionality.
- Removed main loop so that commands are passed through immediately.
- Other small cleanups and refactors.

See original MR for more details: https://gitlab.com/astuff/autoware.ai/core_planning/-/merge_requests/84

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@icolwell-as I'm not a big fan of removing existing APIs without a lot of discussion with the community, especially in the last feature release of the software. Could AStuff reformat this MR to leave that functionality but provide the other improvements?

**Comment by icolwell-as** [comment]
Unfortunately, removing the remote command capabilities is what made it much easier to streamline/simplify the operation of this node.
I'll leave this PR open and take a closer look later to see how much additional work would be required.

**Comment by JWhitleyWork** [comment]
@icolwell-as Any updates?

**Comment by icolwell-as** [comment]
Hi @JWhitleyWork, I think I'll close this PR. In retrospect it was mostly tailored to our specific use case and may not be appropriate for the wider community. Also, we don't really have a clear understanding of the remote control use case in order to make sure its re-implemented and fully tested along with the other control input types.
Thanks!

**Comment by JWhitleyWork** [comment]
Thanks, @icolwell-as.

**Pull request closed without merging**
