### PR TITLE
Add yellow arrows to the global path to indicate turn signal activation

### PR DESCRIPTION
**Pull request by icolwell-as**
Add yellow arrows to the global path that reflect the steering_state field of each waypoint state.

See original MR for more details: https://gitlab.com/astuff/autoware.ai/core_planning/-/merge_requests/43

### CODE REVIEW

**Comment by TakaHoribe** [comment]
@icolwell-as Thank you for this PR. The function looks good, but the formatting doesn't follow the roslint e.g. `offset(0,0,0)` -> `offset(0, 0, 0)` . Could you fix it? 

Just for reference, I attached the diff file [here](https://github.com/Autoware-AI/core_planning/files/5445260/core_planning_roslint_diff.patch.txt).

**Comment by TakaHoribe** [comment]
I've tested in my local. The visualization looks good.
image

**Comment by icolwell-as** [comment]
@TakaHoribe thanks for reviewing and providing an easy patch!

**Review by TakaHoribe — APPROVED** [review]
LGTM.

**Pull request merged**
